[package]
name = "redkey"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["Umpire274 <umpire274@gmail.com>"]
description = "RedKey - PC inventory & diagnostics tool for IT technicians"
homepage = "https://github.com/umpire274/RedKey"
repository = "https://github.com/umpire274/RedKey"
readme = "README.md"

build = "build.rs"

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.43", default-features = false, features = ["clock"] }
egui = "0.33.3"
eframe = { version = "0.33.3", default-features = true }
sysinfo = "0.38.0"
once_cell = "1.21.3"

# Logging (opzionale, utile subito)
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }

[profile.release]
lto = true
codegen-units = 1

[build-dependencies]
winres = "0.1.12"

[package.metadata.winresource]
OriginalFilename = "redkey.exe"
FileDescription = "RedKey - IT Specialist Diagnostic Tool"
ProductName = "RedKey"
ProductVersion = "0.1.0"
LegalCopyright = "© 2025 Alessandro Maestri"
Icon = "res/redkey.ico"
